env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: "x64"
    binary: fgr
    ldflags: -s -w -X fg/cmd.Version={{ .Version }}
    goos:
      - linux
      - freebsd
      - windows
      - openbsd
      - netbsd
      - darwin
    goarch:
      - amd64

  - id: "386"
    binary: fgr
    ldflags: -s -w -X fg/cmd.Version={{ .Version }}
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386

  - id: "arm"
    binary: fgr
    ldflags: -s -w -X fg/cmd.Version={{ .Version }}
    goos:
      - linux
      - freebsd
    goarch:
      - arm
    goarm:
      - 7

  - id: "arm64"
    binary: fgr
    ldflags: -s -w -X fg/cmd.Version={{ .Version }}
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - arm64

archives:
  - id: default
    builds:
      - x64
      - arm
      - arm64
      - 386

brews:
-
    goarm: 7
    tap:
      owner: aegoroff
      name: homebrew-tap
    commit_author:
      name: "Alexander Egorov"
      email: "egoroff@gmail.com"
    test: |
        assert_match version.to_s, shell_output("#{bin}/fgr ver")
    homepage: "https://github.com/aegoroff/fg"
    description: "Small console app written in Go that allows you to easily group all files in the dir specified"
    license: "Apache-2.0"

scoop:
  bucket:
    owner: aegoroff
    name: scoop-bucket
  homepage:  https://github.com/aegoroff/fg
  description: Small console app written in Go that allows you to easily group all files in the dir specified into several child directories.
  license: Apache-2.0

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
