env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: "x64"
    binary: fg
    ldflags: -s -w -X fg/cmd.Version={{ .Version }}
    goos:
      - linux
      - freebsd
      - windows
      - openbsd
      - solaris
      - netbsd
      - darwin
    goarch:
      - amd64

  - id: "386"
    binary: fg
    ldflags: -s -w -X fg/cmd.Version={{ .Version }}
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386

  - id: "arm"
    binary: fg
    ldflags: -s -w -X fg/cmd.Version={{ .Version }}
    goos:
      - linux
      - freebsd
    goarch:
      - arm
      - arm64
    goarm:
      - 7

archives:
  - id: default
    builds:
      - x64
      - arm
      - 386

brews:
-
    goarm: 7
    tap:
      owner: aegoroff
      name: homebrew-tap
    commit_author:
      name: "Alexander Egorov"
      email: "egoroff@gmail.com"
    homepage: "https://github.com/aegoroff/fg"
    description: "A small commandline app written in Go that allows you to easily group all files in the dir specified into several child directories."

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
