# version format
version: 0.1.{build}

clone_folder: c:\gopath\src\fg

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\usr\bin;%PATH%
  - go version
  - go env
  - go get -u "github.com/stretchr/testify/assert"
  - go get -u "github.com/spf13/afero"
  - go get -u "github.com/spf13/cobra"
  - go get -u "github.com/aegoroff/godatastruct/collections"

stack: go 1.13

image: Visual Studio 2017

build_script:
  - go build -ldflags "-X fg/cmd.Version=%APPVEYOR_BUILD_VERSION%" fg

test_script:
  - go test -coverprofile=coverage.txt -covermode=atomic fg/...

after_test:
  - ps: |
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.txt" -t $env:CODECOV_TOKEN

artifacts:
  - path: fg.exe
    name: binary

